### ISSUE TITLE
Problems after installing

### ISSUE THREAD

**Issue by ingramr88** [kpolley/Python_AVrecorder#3]
I am a super noob but would like to use this code if it works. after install, when I try to run picam.py on my raspberry pi 4 running raspbian, I get 

Traceback (most recent call last):
  File "picam.py", line 5, in <module>
    from AudioRecorder import AudioRecorder
  File "/home/pi/Python_AVrecorder/AudioRecorder.py", line 24
    print(status, file=sys.stderr)

Any advice on how to procceed? I am using a usb webcam that also is a microphone and I have external speakers hooked up. Thanks!

**Comment by kpolley** [comment]
Hi! Sorry for the late reply...are you running this on Python3 or 2? I think for Python2 you need to import the file differently like so

`from .AudioRecorder import AudioRecorder`

let me know if your still having issues

**Comment by fagol** [comment]
Ingramr88 : 
is your project working?

**Comment by ingramr88** [comment]
Which project are you referring to?

**Comment by ingramr88** [comment]
> Ingramr88 :
> is your project working?

I got the camera module working. Yes

**Comment by fagol** [comment]
the project about your raspberry PI4 and webcam?

**Comment by fagol** [comment]
And the audio with video is Ok too?

**Comment by ingramr88** [comment]
Ok. I didn't get the python code to work with it.  I switched tracks and
started working on building the microscope. Wanted then pi camera to record
audio and video for the microscope.

**Comment by fagol** [comment]
ok i understand you used a pi camear instead of the webcam, is that it? (excuse my language, i am french)

**Comment by ingramr88** [comment]
yes, I am using the raspberry pi camera as the eyepiece for the microscope
so it can record the specimen in real time. wanted to use python to control
the video/audio.

**Comment by fagol** [comment]
ok, so you record the sound with a usb microphone, is that it?

**Comment by ingramr88** [comment]
Actually....the sound isnt as important. I can do without that.

**Comment by fagol** [comment]
I ask you all these questions because I use a rapberry with a pi camera and a usb microphone. the whole works, but I have a delay between the sound and the video .
So i understand that you can not help me?

**Comment by ingramr88** [comment]
Aha! I see. I was having that issue too. I cannot help you. I only really
needed that video. Once I noticed the delay, I quit using audio.

**Comment by fagol** [comment]
thanks a lot for your time.
good continuation
fabrice
